export const SYSTEM_ROLE_LIST = 'SYSTEM_ROLE_LIST';
export const SYSTEM_ROLE_STATUS = 'SYSTEM_ROLE_STATUS';
export const SYSTEM_ROLE_SCANALL = 'SYSTEM_ROLE_SCANALL';
export const SYSTEM_DICTIONARY_LIST = 'SYSTEM_DICTIONARY_LIST';

export const LANGUAGE = 'LANGUAGE';
export const POWERS = 'POWERS';// 权限码

